FROM ghcr.io/puppeteer/puppeteer:23.6.0

# Skip Chromium download since it’s already in the Docker image
ENV PUPPETEER_SKIP_DOWNLOAD=true

WORKDIR /usr/src/app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm ci
COPY . .

# Command to start the application
CMD ["node", "server.mjs"]
